# https://github.com/DavidAnson/vscode-markdownlint?tab=readme-ov-file#rules
line-length:
  line_length: 120
  heading_line_length: 80
  code_block_line_length: 120
  code_blocks: true
  tables: true
  headings: true
  strict: false
  stern: false
no-inline-html: false
no-bare-urls: false
no-duplicate-heading: false
